ISSUE_TEMPLATES = [
    "Hi, my headphones don\u2019t power on at all. No lights, no sound, and charging doesn\u2019t work despite trying multiple cables and adapters.",
    "Hello, I can\u2019t get my headphones to turn on. They don\u2019t show any charging light and remain completely unresponsive.",
    "Hi support, the headphones won\u2019t charge or light up. I tested several outlets and chargers, but nothing happens.",
    "Hello, my device seems dead \u2014 no LED indicators, no sound, no response when trying to power it on or charge it.",
    "Hi, I\u2019ve attempted to charge my headphones with different chargers, but there\u2019s no reaction at all.",
    "Hello, the headphones refuse to turn on. No charging indication appears, even after using multiple cables.",
    "Hi support, my headphones appear completely unresponsive. No lights during charging and they don\u2019t power on.",
    "Hi, I\u2019ve tried various outlets and USB cables, but the headphones won\u2019t charge or show any activity.",
    "Hello, I cannot get any lights or sounds from my headphones. They don\u2019t react to chargers or resets.",
    "Hi support, the device won\u2019t start or charge. I tested several cables, nothing seems to work.",
    "Hello, the headphones don\u2019t respond to button presses and don\u2019t light up when plugged in.",
    "Hi, charging doesn\u2019t seem to do anything. No LED indicator shows up, and they won\u2019t turn on.",
    "Hello, I\u2019ve attempted resetting them, but the headphones still won\u2019t charge or power on.",
    "Hi, the device is fully unresponsive. No charging light, no sound, multiple cables tested.",
    "Hello, my headphones won\u2019t turn on even after leaving them plugged in for hours. No indicator lights appear.",
    "Hi support, I plugged the headphones into different chargers but they still show no signs of life.",
    "Hello, the device does not react to charging and won\u2019t power on. I tried a reset with no improvement.",
    "Hi, I\u2019ve tested several USB chargers, but the headphones remain completely dead.",
    "Hello, charging doesn\u2019t activate any lights and the headphones won\u2019t turn on afterward.",
    "Hi support, the device is unresponsive to both charging and button presses.",
    "Hello, I\u2019ve used multiple cables and outlets but the headphones don\u2019t charge or power up.",
    "Hi, my headphones seem dead \u2014 no charging LED appears and they won\u2019t turn on.",
    "Hello, I cannot get the device to react to charging or resets. Completely unresponsive.",
    "Hi, even with different adapters, the headphones don\u2019t show any charging indication.",
    "Hello support, the device doesn\u2019t power on and there\u2019s no sign of charging activity.",
    "Hi, I tried charging through several USB ports, but the headphones stay inactive.",
    "Hello, the headphones produce no lights or sounds and they won\u2019t respond to any charger.",
    "Hi support, nothing happens when I press the power button or plug in the charger.",
    "Hello, the device doesn\u2019t take charge nor show any indicator lights.",
    "Hi, I attempted a reset and used different chargers, but the headphones remain dead.",
    "Hello, my headphones don\u2019t react to power or charging attempts at all.",
    "Hi support, no matter which cable I use, there\u2019s no charging light or startup response.",
    "Hello, the device won\u2019t charge or turn on, even after testing various power sources.",
    "Hi, my headphones are not responding \u2014 no LED, no sound, completely inactive.",
    "Hello, I plugged them in for charging but nothing lights up and the device won\u2019t start.",
    "Hi support, I\u2019ve tried several charging setups, but the headphones remain lifeless.",
    "Hello, the device doesn\u2019t start, and charging attempts don\u2019t trigger any lights.",
    "Hi, even after switching adapters, the headphones don\u2019t show any charging activity.",
    "Hello, my headphones don\u2019t react to resets or charging.",
    "Hi support, the device stays unresponsive regardless of the cable or outlet used.",
    "Hello, I can\u2019t get the headphones to turn on or show a charging light, no matter what cable I use.",
    "Hi, I\u2019ve tested different chargers and tried resetting, but the headphones won\u2019t power up.",
    "Hello, the device seems to be completely dead \u2014 no charging indication, no response.",
    "Hi support, I cannot turn on the headphones and they won\u2019t charge either.",
    "Hello, I attempted multiple cables and outlets but there\u2019s zero reaction from the device.",
    "Hi, the headphones do not show any LED or respond to power button presses.",
    "Hello, I\u2019ve tried various charging accessories, but the headphones won\u2019t power or charge.",
    "Hi support, the device doesn\u2019t take any charge and remains unresponsive after resets.",
    "Hello, no lights appear during charging and the headphones won\u2019t turn on at all.",
    "Hi, I tested several chargers, but the headphones still don\u2019t react in any way."
]