ISSUE_TEMPLATES = [
    "Hi, my headphones don\u2019t power on at all. No lights, no sound, and charging doesn\u2019t work despite trying multiple cables and adapters.",
    "Hello, I can\u2019t get my headphones to turn on. They don\u2019t show any charging light and remain completely unresponsive.",
    "Hi support, the headphones won\u2019t charge or light up. I tested several outlets and chargers, but nothing happens.",
    "Hello, my device seems dead \u2014 no LED indicators, no sound, no response when trying to power it on or charge it.",
    "Hi, I\u2019ve attempted to charge my headphones with different chargers, but there\u2019s no reaction at all.",
    "Hello, the headphones refuse to turn on. No charging indication appears, even after using multiple cables.",
    "Hi support, my headphones appear completely unresponsive. No lights during charging and they don\u2019t power on.",
    "Hi, I\u2019ve tried various outlets and USB cables, but the headphones won\u2019t charge or show any activity.",
    "Hello, I cannot get any lights or sounds from my headphones. They don\u2019t react to chargers or resets.",
    "Hi support, the device won\u2019t start or charge. I tested several cables, nothing seems to work.",
    "Hello, the headphones don\u2019t respond to button presses and don\u2019t light up when plugged in.",
    "Hi, charging doesn\u2019t seem to do anything. No LED indicator shows up, and they won\u2019t turn on.",
    "Hello, I\u2019ve attempted resetting them, but the headphones still won\u2019t charge or power on.",
    "Hi, the device is fully unresponsive. No charging light, no sound, multiple cables tested.",
    "Hello, my headphones won\u2019t turn on even after leaving them plugged in for hours. No indicator lights appear.",
    "Hi support, I plugged the headphones into different chargers but they still show no signs of life.",
    "Hello, the device does not react to charging and won\u2019t power on. I tried a reset with no improvement.",
    "Hi, I\u2019ve tested several USB chargers, but the headphones remain completely dead.",
    "Hello, charging doesn\u2019t activate any lights and the headphones won\u2019t turn on afterward.",
    "Hi support, the device is unresponsive to both charging and button presses.",
    "Hello, I\u2019ve used multiple cables and outlets but the headphones don\u2019t charge or power up.",
    "Hi, my headphones seem dead \u2014 no charging LED appears and they won\u2019t turn on.",
    "Hello, I cannot get the device to react to charging or resets. Completely unresponsive.",
    "Hi, even with different adapters, the headphones don\u2019t show any charging indication.",
    "Hello support, the device doesn\u2019t power on and there\u2019s no sign of charging activity.",
    "Hi, I tried charging through several USB ports, but the headphones stay inactive.",
    "Hello, the headphones produce no lights or sounds and they won\u2019t respond to any charger.",
    "Hi support, nothing happens when I press the power button or plug in the charger.",
    "Hello, the device doesn\u2019t take charge nor show any indicator lights.",
    "Hi, I attempted a reset and used different chargers, but the headphones remain dead.",
    "Hello, my headphones don\u2019t react to power or charging attempts at all.",
    "Hi support, no matter which cable I use, there\u2019s no charging light or startup response.",
    "Hello, the device won\u2019t charge or turn on, even after testing various power sources.",
    "Hi, my headphones are not responding \u2014 no LED, no sound, completely inactive.",
    "Hello, I plugged them in for charging but nothing lights up and the device won\u2019t start.",
    "Hi support, I\u2019ve tried several charging setups, but the headphones remain lifeless.",
    "Hello, the device doesn\u2019t start, and charging attempts don\u2019t trigger any lights.",
    "Hi, even after switching adapters, the headphones don\u2019t show any charging activity.",
    "Hello, my headphones don\u2019t react to resets or charging.",
    "Hi support, the device stays unresponsive regardless of the cable or outlet used.",
    "Hello, I can\u2019t get the headphones to turn on or show a charging light, no matter what cable I use.",
    "Hi, I\u2019ve tested different chargers and tried resetting, but the headphones won\u2019t power up.",
    "Hello, the device seems to be completely dead \u2014 no charging indication, no response.",
    "Hi support, I cannot turn on the headphones and they won\u2019t charge either.",
    "Hello, I attempted multiple cables and outlets but there\u2019s zero reaction from the device.",
    "Hi, the headphones do not show any LED or respond to power button presses.",
    "Hello, I\u2019ve tried various charging accessories, but the headphones won\u2019t power or charge.",
    "Hi support, the device doesn\u2019t take any charge and remains unresponsive after resets.",
    "Hello, no lights appear during charging and the headphones won\u2019t turn on at all.",
    "Hi, I tested several chargers, but the headphones still don\u2019t react in any way."
]

CEFALY_ISSUE_TEMPLATES = [
    "My Cefaly device won't turn on at all, and it doesn't charge even after trying different cables.",
    "I'm unable to power on my Cefaly unit; no lights appear when charging.",
    "The device is completely unresponsive, not turning on or showing any charging indicators.",
    "My Cefaly refuses to start up or charge, despite following all troubleshooting steps.",
    "It seems my Cefaly is dead; it won't power on or hold a charge.",
    "No matter what I do, my Cefaly won't switch on or indicate it's charging.",
    "The unit is lifeless; pressing the button does nothing and charging fails.",
    "I can't get my Cefaly to work; it won't turn on and the charging light is off.",
    "My Cefaly device has stopped working completely; no power, no charging response.",
    "There are no signs of life from my Cefaly; it won't charge or turn on.",
    "My Cefaly unit is unresponsive to the power button and won't charge.",
    "I've tried resetting, but my Cefaly still won't turn on or charge.",
    "The device won't power up, and plugging it in for charging changes nothing.",
    "My Cefaly is not functioning; it won't turn on or show charging status.",
    "I cannot get the Cefaly to power on, and it doesn't seem to charge.",
    "It appears my Cefaly has died; it won't accept a charge or turn on.",
    "My Cefaly unit won't start, and there are no lights when I plug it in.",
    "The Cefaly device is unresponsive; it implies it's not charging or turning on.",
    "I've tried multiple outlets, but my Cefaly won't charge or power on.",
    "My Cefaly won't function; it doesn't turn on and shows no charging light.",
    "The unit is completely dead; it won't charge or respond to the power button.",
    "My Cefaly fails to turn on, and charging calls for no reaction.",
    "I can't turn on my Cefaly, and it doesn't appear to be charging.",
    "The device is totally unresponsive; no power, no charging indication.",
    "My Cefaly doesn't work; it won't power up or take a charge.",
    "I'm having trouble with my Cefaly; it won't turning on or charge.",
    "The Cefaly unit is unresponsive to charging and won't power on.",
    "My Cefaly seems defective; it won't turn on or show any lights.",
    "The device refuses to power on, and charging doesn't help.",
    "I can't get a response from my Cefaly; it won't charge or turn on.",
    "My Cefaly unit is dead; flashing lights are absent, and it won't start.",
    "The Cefaly won't power on, and the battery doesn't seem to charge.",
    "My device is inactive; it won't turn on or show charging progress.",
    "I've followed the guide, but my Cefaly won't charge or power on.",
    "The Cefaly doesn't respond to the button or the charger.",
    "My Cefaly stays off; it won't charge or turn on.",
    "The unit won't start up, and charging provides no feedback.",
    "My Cefaly is not working; no power, no charging light.",
    "I can't switch on my Cefaly, and it won't charge.",
    "The device is lifeless; it won't turn on or recharge.",
    "My Cefaly has no power and won't charge even with different cables.",
    "The unit refuses to turn on, and charging seems to fail.",
    "My Cefaly won't activate, and it doesn't show it's charging.",
    "I am unable to use my Cefaly; it won't power on or charge.",
    "The device is totally dead; no response to charging or power.",
    "My Cefaly won't turn on, and I see no charging indicators.",
    "The unit is unresponsive; it won't charge or power up.",
    "My Cefaly seems broken; it won't turn on or charge.",
    "The device won't start, and charging has no effect.",
    "I can't get my Cefaly to work; it refuses to charge or turn on.",
    "My Cefaly is unresponsive; no lights, no power.",
    "The unit won't power on, and it doesn't appear to be charging.",
    "My Cefaly device is dead; it won't turn on or charge.",
    "I'm unable to power up my Cefaly; charging does nothing.",
    "The device won't turn on, and the charging light is missing.",
    "My Cefaly refuses to function; no power, no charge.",
    "The unit is completely unresponsive to power and charging.",
    "My Cefaly won't start, and it doesn't seem to take a charge.",
    "The device is dead; it won't turn on or show charging signs.",
    "My Cefaly is inactive; it won't power on or charge.",
    "I can't get any response from my Cefaly; no power, no charge.",
    "The unit won't turn on, and charging is unsuccessful.",
    "My Cefaly seems to be dead; it won't charge or power on.",
    "The device won't activate; charging doesn't seem to work.",
    "My Cefaly is totally unresponsive; it won't turn on.",
    "The unit won't power up, and charging shows no lights.",
    "My Cefaly refuses to start; it won't charge either.",
    "The device is lifeless; no power, no charging indicator.",
    "My Cefaly won't function; it refuses to turn on or charge.",
    "The unit is dead; pressing power does nothing, charging fails.",
    "My Cefaly won't turn on, and it doesn't charge.",
    "The device is unresponsive; it won't power on or charge.",
    "My Cefaly seems defective; no power, no charging light.",
    "The unit refuses to power on, and charging is ineffective.",
    "My Cefaly has stopped working; it won't charge or turn on.",
    "The device is unresponsive to charging and won't start.",
    "My Cefaly won't power on; charging results in nothing.",
    "The unit is completely dead; it won't turn on or charge.",
    "My Cefaly refuses to work; no power, no charging.",
    "The device won't turn on, and charging indicators are off.",
    "My Cefaly is unresponsive; it fails to charge or power on.",
    "The unit won't start up; charging doesn't help.",
    "My Cefaly remains off; it won't charge or turn on.",
    "The device is dead; no response to power or charging.",
    "My Cefaly won't activate; it doesn't appear to charge.",
    "The unit is lifeless; it refuses to turn on or charge.",
    "My Cefaly has no power; it won't charge or start.",
    "The device won't turn on, and charging doesn't work.",
    "My Cefaly is unresponsive to power button and charging.",
    "The unit will not power on; charging shows no activity.",
    "My Cefaly seems dead; it won't turn on or accept a charge.",
    "The device refuses to start; charging produces no light.",
    "My Cefaly is completely inactive; it won't power on.",
    "The unit won't turn on, and it fails to charge.",
    "My Cefaly is dead; it won't charge or power up.",
    "The device is unresponsive; no power or charging signs.",
    "My Cefaly won't function at all; no charge, no power.",
    "The unit refuses to turn on; charging is not working.",
    "My Cefaly is unresponsive; it won't turn on or charge.",
    "The device is dead; it won't power on or show charging status."
]